server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: org.mariadb.Driver
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    open-in-view: fasle
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.default_batch_fetch_size]': 100

logging:
  level:
    '[com.jooyoung.bank]': INFO